import "./ChangeAvatar";
import "./ChangePassword";
import "./CreateAccount";
import "./ForgotPassword";
import "./ForgotPasswordMail";
import "./AllUsers";
import "./Login";
import "./Profile";
import "./VerifyMail";
import "./VerifyToken";
import "./UserAdminPage";
import "./RefreshToken"
