export enum Routes {
    INDEX = "/",
    LOGIN = "/login",
    CREATEACCOUNT = "/createaccount",
    POST = "/post",
    POSTCREATE = "/post/create",
    QUESTION = "/question",
    TOPIC = "/topic",
    USERDASHBOARD = "/user",
    ADMINDASHBOARD = "/admin",
    UNSAVEDPOSTS = "/unsavedposts",
    UNSAVEDQUESTIONS = "/unsavedquestions",
    WIPPOSTS = "/wipposts",
    SEARCH = "/search",
    FORGOTPASSWORD = "/forgotpassword",
}
